name: Docker Image Build and Push

on:
  push:
    branches:
      - main
    paths:
      - "version"
  workflow_dispatch:

env:
  GHCR_REPO: ghcr.io/${{ github.repository_owner }}/dnspod-webhook
  DOCKERHUB_REPO: docker.io/${{ secrets.DOCKERHUB_USERNAME }}/dnspod-webhook

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
      id-token: write
      actions: write
    strategy:
      matrix:
        platform: [linux/amd64, linux/arm64]
        
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Read version from VERSION file
        id: get_version
        run: |
          VERSION=$(cat version)
          echo "VERSION=$VERSION" >> $GITHUB_ENV

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
        with:
          platforms: ${{ matrix.platform }}

      - name: Login to GHCR
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          registry: docker.io
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push Docker image
        id: docker-build
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          platforms: ${{ matrix.platform }}
          tags: |
            ${{ env.GHCR_REPO }}:${{ env.VERSION }}
            ${{ env.GHCR_REPO }}:latest
            ${{ env.DOCKERHUB_REPO }}:${{ env.VERSION }}
            ${{ env.DOCKERHUB_REPO }}:latest
          build-args: |
            VERSION=${{ env.VERSION }}